### ISSUE TITLE
[Feature request] Chapter/Episode "difference"

### ISSUE THREAD

**Issue by Damselflies** [Koopzington/anitools#196]
Hi ! 
I would like to request a feature to see how many episode/chapters there are left to read/watch from finished works, so it would only use already existing data. Just a simple (Chapter/episode count) - (Chapter/episode progress) = (Chapters/episodes difference).
There is no way on Anilist itself to see how many chapters you have left of something without calculating it yourself and I personally like to do "finish marathons" were I try to finish as many paused works in 1 sitting, so that means I every time have to calculate which ones have the least amount of chapter/episodes left to watch, so I can bang out multiple ones. Would love if anitools could do this for me <3

Greetings

**Comment by Koopzington** [comment]
Implemented and live!
