### ISSUE TITLE
format filters by media type

### ISSUE THREAD

**Issue by scosmin98423** [Koopzington/anitools#21]
the format filters options should change by media type chosen(anime or manga). atm there are only anime format filters.
![image](https://github.com/Koopzington/anitools/assets/3026973/537ac635-f1bc-4288-a222-62b7520551c6)

**Comment by Koopzington** [comment]
Should work again now (https://github.com/Koopzington/anitools/commit/0f9313fd591c5ef7852cae9738fe0e832c9a4be7)
